spring:
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: nboniello466@gmail.com
    password: Milanista1997
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
apiKey : "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"
